const markers = [
  {
    id: 1,
    city: "Amur Leopard",
    // icon: "AmurLeopard.png",
    color: "gold",
    coordinates: [51, 123],
    value: 50,
  },
  {
    id: 2,
    city: "Black-flanked Rock-wallaby",
    color: "gold",
    coordinates: [-33, 125],
    value: 35,
  },
  {
    id: 3,
    city: "Black Rhino",
    color: "gold",
    coordinates: [12, 36],
    value: 35,
  },
  {
    id: 4,
    city: "Whale Shark",
    color: "gold",
    coordinates: [-14, 115],
    value: 135,
  },
  {
    id: 5,
    city: "Orangutan",
    color: "gold",
    coordinates: [-11, 99],
    value: 80,
  },
  {
    id: 6,
    city: "Hawksbill Turtle",
    color: "gold",
    coordinates: [28, -85],
    value: 54,
  },
  {
    id: 7,
    city: "Red Panda",
    color: "gold",
    coordinates: [27, 103],
    value: 54,
  },
  {
    id: 8,
    city: "Black Footed Ferret",
    color: "gold",
    coordinates: [48, -105],
    value: 54,
  },
  {
    id: 9,
    city: "Seaions",
    color: "gold",
    coordinates: [-4.5, -92],
    value: 54,
  },
  {
    id: 10,
    city: "Orangutan",
    color: "gold",
    coordinates: [14, 115],
    value: 54,
  },
  {
    id: 11,
    city: "Cross River Gorilla",
    color: "gold",
    coordinates: [12, 22],
    value: 54,
  },
  {
    id: 12,
    city: "Eastern Curlew",
    color: "gold",
    coordinates: [-20, 123],
    value: 54,
  },
  {
    id: 13,
    city: "Eastern Lowland Gorilla",
    color: "gold",
    coordinates: [12, 10],
    value: 54,
  },
  {
    id: 14,
    city: "Gouldian Finch",
    color: "gold",
    coordinates: [-33, 140],
    value: 54,
  },
  {
    id: 15,
    city: "Javan Rhino",
    color: "gold",
    coordinates: [-4, 93],
    value: 54,
  },
  {
    id: 16,
    city: "Porpoise",
    color: "gold",
    coordinates: [35, 113],
    value: 54,
  },
  {
    id: 17,
    city: "Quoll",
    color: "gold",
    coordinates: [-20, 138],
    value: 54,
  },
  {
    id: 18,
    city: "Sumatran Elephant",
    color: "gold",
    coordinates: [-1, 115],
    value: 54,
  },
  {
    id: 19,
    city: "Sunda Tiger",
    color: "gold",
    coordinates: [9, 93],
    value: 54,
  },
  {
    id: 20,
    city: "Continental Tiger",
    color: "gold",
    coordinates: [25, 93],
    value: 54,
  },
  {
    id: 21,
    city: "Vaquitas",
    color: "gold",
    coordinates: [35, -110],
    value: 54,
  },
  {
    id: 22,
    city: "African Wild Dog",
    color: "gold",
    coordinates: [-20, 25],
    value: 54,
  },
  {
    id: 23,
    city: "Asian Elephants",
    color: "gold",
    coordinates: [35, 90],
    value: 54,
  },
  {
    id: 24,
    city: "Blue Whale",
    color: "gold",
    coordinates: [-35, -75],
    value: 54,
  },
  {
    id: 25,
    city: "Bonobo",
    color: "gold",
    coordinates: [-4.038333, 18],
    value: 54,
  },
  {
    id: 26,
    city: "Green Turtle",
    color: "gold",
    coordinates: [12, -92],
    value: 54,
  },
  {
    id: 27,
    city: "Hector Dolphin",
    color: "gold",
    coordinates: [-49, 177],
    value: 54,
  },
  {
    id: 28,
    city: "Indian Elephant",
    color: "gold",
    coordinates: [28, 75],
    value: 54,
  },
  {
    id: 29,
    city: "Mountain Gorilla",
    color: "gold",
    coordinates: [-1, 31],
    value: 54,
  },
  {
    id: 30,
    city: "Whale",
    color: "gold",
    coordinates: [-20, -75],
    value: 54,
  },
  {
    id: 31,
    city: "Whale Shark",
    color: "gold",
    coordinates: [12, -75],
    value: 54,
  },
];
export default markers;
